[DEFAULT]
source = /home/sanjayan/Important
destination = /home/sanjayan/Backup
exclude_patterns = 
retention_policy = none
incremental = no
compression = yes
encryption = no
password = 
schedule = 
backup_interval_days = 0
backup_name_template = {timestamp}
notifications_enabled = no

[Backup]
source_dir = /home/sanjayan/Arch_Proj/my_important_data
dest_dir = /home/sanjayan/Arch_Proj/my_backup_storage
backup_interval_days = 1
retention_days = 7
excludes = *.log, __pycache__/

[Logging]
log_file = backup.log

